# Generated by Django 4.1.5 on 2023-05-07 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesetting', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SitesFiles',
        ),
        migrations.AlterField(
            model_name='faq',
            name='ans',
            field=models.TextField(max_length=555),
        ),
    ]
